language: python

python:
 - "3.6"
 - "3.5"

env:
 - DJANGO_SETTINGS_MODULE: lightil.settings_test

sudo: false

services: mysql

branches:
  only:
  - master
  - develop

before_script:
 - mysql -e 'CREATE DATABASE IF NOT EXISTS lightil CHARACTER SET utf8 COLLATE utf8_general_ci;'

install:
 - pip install -r requirements.txt
 - pip install codecov

script: coverage run manage.py test test

after_success:
 - codecov